export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";


export const GET_CART_LIST_REQUEST = "GET_CART_LIST_REQUEST";
export const GET_CART_LIST_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_LIST_FAIL ="GET_CART_LIST_FAIL";

export const  REMOVE_CART_ITEM = 'REMOVE_CART_ITEM' ;
export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO';